name: Publish documentation
on:
  workflow_run:
    workflows: ["Build and test"]
    branches:
      - master
    types:
      - completed
jobs:
  publish-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allows pushing to the `gh-pages` branch
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: SebRollen/toml-action@v1.0.2
      id: read_rust_toolchain
      with:
        file: rust-toolchain
        field: toolchain.channel
    - uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ steps.read_rust_toolchain.outputs.value }}
        components: clippy, rustfmt
    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: possum-build
    - name: Build documentation
      run: |
        cargo doc --no-deps
    - name: Deploy documentation to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: target/doc
